# Generated by Django 6.0.6 on 2026-07-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('current', models.FloatField()),
                ('torque', models.FloatField()),
                ('speed', models.FloatField()),
                ('health', models.FloatField()),
            ],
        ),
    ]
