# Generated by Django 6.0.6 on 2026-07-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('mode_auto', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=2)),
                ('fault_mode', models.CharField(default='normal', max_length=50)),
            ],
        ),
    ]
